version: "3.9"

services:
  frontend:
    build: ./FrontEnd/
    ports:
      - "3000:3000"
  
  backend:
    build: ./Backend/
    ports:
      - "80:80"
  
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: montero
      POSTGRES_USER: montero